[ gen, refactor ] Replaced `MaybeEmptyDeep` with a proof of non-emptiness
buzden/deptycheck pull request #212
Opened 2024-11-11 10:03 UTC by spcfox

More concrete compile-level proofs allow for simpler runtime code. `MaybeEmptyDeep` was replaced with `IsNonEmpty` predicate.

2025-02-28 14:06 UTC, spcfox commented
Comparing this branch to `master` on [Verilog-model ](https://github.com/DepTyCheck/verilog-model) with parameters `--seed 0,1 -n 10 --silent`

![deptycheck_models_verilog_whisker](https://github.com/user-attachments/assets/7910bb17-f38b-4751-aff6-c0441358a254)

2025-03-03 12:16 UTC, buzden requested changes

2025-03-03 12:16 UTC, buzden commented on src/Test/DepTyCheck/Gen.idr
> +strengthen : Gen em a -> Maybe $ Gen em a
This function seems to change semantics, thus, maybe, it should be renamed or something. Originally it was used to match original `em` with the required one, if possible. Not `em` is the same in the start and in the end

2025-03-03 12:16 UTC, buzden commented on src/Test/DepTyCheck/Gen.idr
> +  strengthen : GenAlternatives ne em a -> Maybe $ GenAlternatives True em a
Seemingly, the same comment as for `strengthen` for `Gen`s

2025-03-04 04:10 UTC, spcfox commented on src/Test/DepTyCheck/Gen.idr
> +  strengthen : GenAlternatives ne em a -> Maybe $ GenAlternatives True em a
This `strengthen` has not been changed, it guarantees a non-empty list, not generators
https://github.com/buzden/deptycheck/blob/b7082a2a3a5d4b44ec7eea32c2c293221b431fc4/src/Test/DepTyCheck/Gen.idr#L285-L287

2025-03-04 14:15 UTC, merged